ngrok/ngrok-docs

docs/cloud-edge/modules/webhook.md, docusaurus.config.js
related to : https://github.com/ngrok/ngrok-docs/issues/81
=> enable edits link and fix typo.

docs/integrations/okta/sso-oidc.md
=> Update okta support for ngrok app

docs/guides/securing-your-tunnels.md
Changes:
- I reordered the points to be under sections for Agent, Tunnel, API, and Dashboard which is closer to our other guides and white papers.
- Added a link to setting up Dashboard SSO
- Added "Using a custom ingress domain" under Agent to tell the end user how to set it up
- Added "Blocking non-corporate accounts" to ensure admins can control access
=> update for adding tunnel management

docs/errors/details/_err_ngrok_3200.md
improvements based on https://www.notion.so/ngrok/Error-Page-for-Error-3200-a8f212635d49464eaa38bae5af1f622e
FYI @samcrichard
=> fix: improve wording of 3200 troubleshooting page

docs/cloud-edge/modules/webhook.md
=> feat: adding twitter as a webhook verifier

docs/ngrok-agent/index.md
closes https://github.com/inconshreveable/ngrok/issues/895
=> fix: remove NGROK_API_KEY

docs/api/resources/edge-route-webhook-verification-module.mdx, docs/api/resources/edges-https-routes.mdx, docs/api/resources/edges-https.mdx, docs/api/resources/https-edge-route-webhook-validation-module.mdx, docs/events/_edge-route-webhook-verification-replace.md, docs/events/_endpoint-configuration-create.md, docs/events/_endpoint-configuration-list.md, docs/events/_endpoint-configuration-update.md, docs/events/_endpoint-configuration.md, docs/events/_endpoint-webhook-validation-replace.md, docs/events/_endpoint-webhook-validation.md, docs/events/_https-edge-list.md, docs/events/_https-edge-route-create.md, docs/events/_https-edge-route-update.md, docs/events/_https-edge-route.md, docs/events/_https-edge.md
=> fix: update webhook verification module link

.github/workflows/deploy.yml
Temporarily commenting out the dev s3 sync
=> Temporarily disable dev s3 sync for broken permissions

docs/errors/err_ngrok_4402.mdx
Fixing per support ticket opened. This language was confusing.
=> Change language around adding another user.

docs/overview.md
Added new wording to help with feature discoverability, especially for connectivity
=> Added connect, secure, observe

docs/secure-tunnels/tunnels/ssh-reverse-tunnel-agent.md
somehow the changes from a previous commit were lost. bringing them back over.
=> fix: updating to use v2 commands

docs/ngrok-agent/index.md
Reverts ngrok/ngrok-docs#188
This was added back
=> Revert "fix: remove NGROK_API_KEY"

docs/ngrok-agent/ngrok.md
oauth-client-id and oauth-client-secret were missing
=> fix: added missing oauth params

docs/best-practices/security-dev-productivity/security-dev-productivity.md, docs/cloud-edge/modules/webhook.md, docs/getting-started.md, docs/guides/how-to-set-up-a-custom-domain.md, docs/guides/load-balancing-with-cloud-edges.md
fixes some 404s in the security best practices, also updates some urls to avoid 302s.
=> fix: fixing 404s and 302s

docs/guides/index.md
fixing broken link on load balancing guide
=> fix: broken link

docs/guides/how-to-round-robin-load-balance-with-ngrok-cloud-edges.mdx
fixes an example in the guide page
=> fix: update cli for creating edges

docs/using-ngrok-with/rust.md
Add config (otherwise the app doesn't work)
=> Add config

docs/ngrok-agent/changelog.md
This is a bugfix release; not much to say but it sure is worth shipping
=> ngrok-agent: changelog for v3.2.2

apis/api.md, docs/_faq.md, docs/best-practices/security-dev-productivity/security-dev-productivity.md, docs/cloud-edge/edges/https.md, docs/cloud-edge/modules/index.md, docs/cloud-edge/modules/oauth/github.md, docs/cloud-edge/modules/oauth/index.md, docs/cloud-edge/modules/webhook.md, docs/errors/_err_list_manual.md, docs/errors/_err_ngrok_list.md, docs/errors/err_ngrok_1657.mdx, docs/errors/err_ngrok_1658.mdx, docs/errors/index.html, docs/getting-started.md, docs/integrations/aftership/index.mdx, docs/integrations/aftership/webhooks.md, docs/integrations/docusign/index.mdx, docs/integrations/github/webhooks.md, docs/integrations/gitlab/webhooks.md, docs/integrations/twilio/webhooks.md
fixes minor capitalizations across the docs
=> fix: update capitalizations

docs/using-ngrok-with/k8s.md
- fixed typos
- made it more obvious that you need a custom subdomain
=> fix: updates to the k8s ingress page

docs/using-ngrok-with/k8s.md
took a crack at it. open to suggestions.
=> fix: updating example for free vs paid domains

docs/guides/index.md, docs/guides/raspberry-pi, docs/guides/raspberry-pi.md, docs/guides/remote-device-mgmt-linux.md
a guide to connecting to your raspberry pi device
=> Create raspberry-pi guide

docs/cloud-edge/modules/webhook.md, docs/getting-started.md, docs/integrations/autodesk/webhooks.md, docs/integrations/brex/webhooks.md, docs/integrations/calendly/webhooks.md, docs/integrations/twitter/webhooks.md, docs/integrations/webex/webhooks.md
closes https://github.com/ngrok/ngrok-docs/issues/157
don't merge until https://github.com/ngrok-private/ngrok/pull/16837 is deployed
=> fix: update autodesk webhook

docs/using-ngrok-with/java.md, docs/using-ngrok-with/node-js.md, docs/using-ngrok-with/python.md
Surface some links for ngrok-js, ngrok-py, and ngrok-java.
=> Add some discoverability for the language SDK's

docs/using-ngrok-with/django.md, docs/using-ngrok-with/flask.md
=> surface python sdk on django+flask

docs/using-ngrok-with.md, docs/using-ngrok-with/fastAPI.md, docs/using-ngrok-with/ftp.md, docs/using-ngrok-with/minecraft.md, docs/using-ngrok-with/mongodb.md, docs/using-ngrok-with/mysql.md, docs/using-ngrok-with/outboundProxy.md, docs/using-ngrok-with/postgresql.md, docs/using-ngrok-with/smtp.md, docs/using-ngrok-with/wordpress.md
adds more examples to the using ngrok with section of the docs.
also fixes #312
=> feat: adding more using with docs

.envrc, .gitignore, README.md, flake.lock, flake.nix
Use direnv, flake and nix to deliver nodejs and pnpm when you get into the docs directory.
=> use direnv/nix/flakes to setup env

docs/cloud-edge/modules/ip-restrictions.md
Same as the work done form mTLS in https://github.com/ngrok/ngrok-docs/pull/370 but now for the IP restrictions module.
=> refactor IP restrictions docs

docs/using-ngrok-with/docker.md
Hi, I was wondering how the different options are provided to the ngrok agent and wasted a bit of time until I finally found out that the convention is basically the same as the agent one - so I bumped the docs to make it more obvious.
=> Update docker.md - examples

docs/api/index.md, docs/errors/reference.md, docs/events/index.mdx
a few other random navigation fixes for consistency
=> document api ip restrictions.

docs/cloud-edge/modules/circuit-breaker.md, docs/cloud-edge/modules/compression.md, docs/cloud-edge/modules/ip-restrictions.md, docs/cloud-edge/modules/mutual-tls.md, docs/cloud-edge/modules/webhook-verification.md
i'm not super happy with the try it out section but i couldn't think of anything better. any ideas?
=> refactor circuit breaker module documentation

docs/secure-tunnels/ngrok-agent/reference/changelog.md
Support for datadog event destinations!
=> agent changelog: add entry for v3.3.2

src/css/custom.css
=> make css more robust against external scripts (e.g. ketch)

docs/cloud-edge/app-users.md, docs/integrations/amazon-eks/eks.md, docs/integrations/auth0/sso-oidc.md, docs/integrations/azure-ad-b2c/sso-saml.md, docs/integrations/azure-ad/sso-saml.md, docs/integrations/consul/k8s.md, docs/integrations/curity/sso-oidc.md, docs/integrations/fusionauth/sso-oidc.md, docs/integrations/jumpcloud/sso-oidc.md, docs/integrations/jumpcloud/sso-saml.md, docs/integrations/miniorange/sso-oidc.md, docs/integrations/miniorange/sso-saml.md, docs/integrations/okta/sso-oidc.md, docs/integrations/okta/sso-saml.md, docs/integrations/trustelem/sso-oidc.md, docs/integrations/trustelem/sso-saml.md, docs/using-ngrok-with/go.md, docs/using-ngrok-with/k8s.md, docs/using-ngrok-with/rust.md
fixing some broken formatting after prettier
=> fix: adjust formatting for tips

static/scripts/fix-redirect.js, vercel.json
a recent change updated the urls for these pages. i think this creates redirects as needed.
=> fix: add redirects for aws pages

docs/secure-tunnels/ngrok-agent/reference/changelog.md
update change log to v3.3.5 to add  UserAgentFilter
=> update change log to add UserAgentFilter

docs/guides/security-dev-productivity/security-dev-productivity.md
https://github.com/facebook/docusaurus/issues/6282#issuecomment-1219697039
=> Add workaround for trailing slash issue.

docs/cloud-edge/pops.md
Small updates to the PoPs page.
=> fix: add us-cal-1 pop

docs/secure-tunnels/ngrok-agent/reference/config.md
Updates the PoPs locations to match the cloud-edges page.
Closes #417
=> fix(agent-config): update PoPs

docs/cloud-edge/modules/user-agent-filter.md
Updating docs to be consistent with actual code
=> Update Config and Rust Sections for UserAgentFilter

docs/user-management/index.md
Found a bunch of typos and grammar issues. Added information about when to use them and create them and added to PAYGO plans.
=> Fix Bot Users Page

docs/cloud-edge/modules/circuit-breaker.md, docs/cloud-edge/modules/compression.md, docs/cloud-edge/modules/ip-restrictions.md, docs/cloud-edge/modules/mutual-tls.md, docs/cloud-edge/modules/oauth.mdx, docs/cloud-edge/modules/openid-connect.md, docs/cloud-edge/modules/request-headers.mdx, docs/cloud-edge/modules/response-headers.mdx, docs/cloud-edge/modules/user-agent-filter.md, docs/cloud-edge/modules/webhook-verification.md
This reverts commit 1365077c62abd14f4086089c2e3c88fdbc75e8b2.
=> Revert "Add links from cloud-edge modules to SDK docs (#437)"

docs/obs/index.mdx, docs/obs/reference.mdx, docs/user-management/index.md
change configuration event name to audit events to incorporate additional events sources
=> change configuration event name to audit events

docs/integrations/amazon/index.mdx, docs/integrations/google/index.mdx, docs/integrations/google/oauth.mdx, package.json, pnpm-lock.yaml
updates docusaurus
also closes #430
=> fix: update docusaurus and fix google

examples/nodejs-sdk/tcp-proxyproto.mdx, examples/nodejs-sdk/tcp-random.mdx, examples/nodejs-sdk/tls-proxyproto.mdx
Found some mis-pastes when grepping through examples.
=> Fix 3 nodejs example headers

docs/agent/changelog.md
ngrok-agent v3.4.0 changelog.
Includes the new upstream TLS verification options.
=> ngrok-agent: changelog for v3.4.0

.github/workflows/deploy.yml, .github/workflows/pr.yml, docusaurus.config.js
we are moving over to the algolia search where they crawl and index our site from their end. should improve docs search like 1000000%
=> feat: switching over to new docsearch

docs/getting-started/go.mdx
The current example doesn't compile.
=> fix: Go SDK Example

docs/agent/version-support-policy.mdx
=> Fixing a split infinitive

docs/agent/index.mdx
just checking off followup TODO items that I didn't manage to get in during the refactor
=> document agent connection+reconnection behaviors

docs/guides/licensing.md
=> Fixed pricing URL typo in licensing.md

docs/api/index.mdx
our API supports CORS but we've never documented how. document the API's CORS behaviors
=> document API CORS behaviors

docs/overview/index.mdx, docusaurus.config.js, src/css/custom.css, tailwind.config.js
=> preload fonts

examples/agent-config/http-request-headers.mdx, examples/agent-config/http-response-headers.mdx
=> fix: headers examples

docs/errors/details/_err_ngrok_8012.md
=> fixes youtube embed in error doc

docs/agent/version-support-policy.mdx
We release 3.5.0 on December 7, updating version support policy with that version.
=> Updating Version Support Policy with 3.5x

docs/integrations/amazon-firehose/event-destination.mdx
Correcting an outdated resource link.
=> Update Firehose event-destination.mdx

docs/agent-sdks/index.mdx
=> Typo in docs

docs/errors/country_restriction.mdx
the url for this would be https://ngrok.com/docs/errors/country_restriction
=> Adding error page for country restrictions

docs/obs/traffic-inspection.mdx, sidebars.js
adding placeholder docs for traffic inspection.
=> feat: initial traffic inspector docs

docs/http/traffic-policy/actions/custom-response.mdx, examples/actions/custom-response.mdx
Updating the new configuration method for `custom-response`
=> custom-response: update configuration

docs/whats-new.mdx, sidebars.js
closes #567 
Open to ideas in formatting before i continue adding past releases.
=> feat: adding a what's new section

docs/http/traffic-policy/expressions.mdx, docs/tcp/traffic-policy/expressions.mdx, docs/tls/traffic-policy/expressions.mdx
add docs and examples for cidr macros
=> add documentation for cidr macros

docs/faq/faq.md
This is a first pass at the port allocation faq entry. Let me know if you want me to add more detail here.
=> Add a blurb about port allocation

docs/guides/using-tls-mutual-authentication.md
Just a tiny typo fix found by @DevMandy.
=> Mutual TLS typo fixes

docs/whats-new.mdx
- `req.Path` support for expressions
- Dark mode updates for Edges
=> Product Updates (Early-March Edition)

docs/agent/cli.mdx
Updated documentation to reference changes from https://github.com/ngrok-private/ngrok/pull/27333
=> update documentation for --policy-file flag to support .json

docs/http/traffic-policy/gallery.mdx
Updates the user-agent filtering gallery text to better describe how it works and how to properly decode sequences in expressions for both YAML and JSON.
=> Update user-agent filtering text in gallery

docs/guides/limits.md
added some info about our abuse interstitial to the free plan limits guide
=> feat: add abuse interstitial

docs/guides/licensing.md, examples/actions/redirect.mdx
change type to redirect instead of custom-response.
=> Fix redirect configuration

docs/agent/api.md, docs/agent/changelog.md, docs/agent/version-support-policy.mdx, docs/whats-new.mdx
=> agent changelog for 3.9.0

.github/workflows/deploy.yml, .github/workflows/pr.yml, package.json
This will fix any warnings/errors we were seeing in CI logs about node version mismatches
=> use node 20 in gh actions

docs/using-ngrok-with/rust.md
=> Fix ngrok-rust links

docs/using-ngrok-with/docker.md
closes https://github.com/ngrok/ngrok-docs/issues/734
=> fix: adding note about using internal addresses in ngrok config files

docs/agent/changelog.md, docs/agent/version-support-policy.mdx, docs/whats-new.mdx
Also ngrok-rust, ngrok-javascript, ngrok-python releases in what's new.
=> agent release 3.10.0

docs/http/traffic-policy/expressions/variables.mdx
Resolves https://github.com/ngrok-private/ngrok/issues/29028
=> chore: Add new contenttype variables to req/res

docs/http/traffic-policy/expressions/variables.mdx, docs/tcp/traffic-policy/expressions/variables.mdx, docs/tls/traffic-policy/expressions/variables.mdx
Resolves https://github.com/ngrok-private/ngrok/issues/30076
=> bugfix: Properly Format variables doc Links

docs/http/traffic-policy/actions/url-rewrite.mdx, examples/actions/url-rewrite.mdx
Bikeshedding and wordsmithing welcome.
=> add new doc changes for url-rewrite

docs/http/traffic-policy/expressions/variables.mdx
Resolves https://github.com/ngrok-private/ngrok/issues/30409
=> chore: Add new content_encoding variable to req/res

docs/http/traffic-policy/expressions/variables.mdx
Resolves https://github.com/ngrok-private/ngrok/issues/30477
=> chore: Add new client_port variable to conn

docs/agent/config.mdx, docs/using-ngrok-with.md, docs/using-ngrok-with/rtmp.md
adds docs for https://github.com/ngrok/ngrok/issues/10
also adds using ngrok with rtmp based on user search data.
=> fix: adding rtmp and connect_interface

docs/agent/config.mdx
Adds a sentence about and example of the command `ngrok start --all`
=> Add `ngrok start --all`

README.md
Add step to run `pnpm run fmt` locally before opening a PR
=> Add step to README

docs/http/traffic-policy/actions/url-rewrite.mdx
=> fix copy-text and make docs ngrok rock!

docs/agent/index.mdx
Updated CRL domain to be [crl.ngrok-agent.com](http://crl.ngrok-agent.com/).
=> update crl domain

examples/agent-cli/tcp-traffic-policy.mdx, examples/agent-cli/tls-traffic-policy.mdx, examples/go-sdk/tcp-traffic-policy.mdx, examples/go-sdk/tls-traffic-policy.mdx, examples/k8s/tcp-traffic-policy.mdx, examples/k8s/tls-traffic-policy.mdx
ip addresses need to be quoted
=> fix expression examples in traffic policy modules

docs/agent/index.mdx, docs/faq/faq.md
=> fix: adding info about our agent urls and ips

docs/agent-sdks/index.mdx, docs/k8s/index.mdx
Fixes https://github.com/ngrok-private/ngrok/issues/31192 and another self-referential link for agent SDKs page
=> Fix bottom next links

.github/workflows/ci-checks.yml, docusaurus.config.ts
Pragmatic solution for now until we tackle https://github.com/ngrok/ngrok-docs/issues/869
=> Switch docusaurus broken links config from error to warn

docs/errors/index.md
This is a way to gauge interest in and get feedback for customized error pages for traffic.
=> Update error page to have dev preview for custom error page

docs/errors/index.md
broken by me merging https://github.com/ngrok/ngrok-docs/pull/868
=> fix broken link

docs/using-ngrok-with.md, docs/using-ngrok-with/laravel.md
saw that users were searching our docs for laravel and getting no results.
=> feat: adding simple page about laravel

docs/guides/licensing.md
We want all limits clearly in one single place in our docs.
=> Update licensing doc to have limits 

docs/agent/config/v3.mdx
=> title is too long and cumbersome for submenu

docs/agent/config/v3.mdx
Resolves #https://github.com/ngrok/ngrok-docs/issues/917
More work is need to break apart the "full example" into multiple smaller and easier to understand examples, but I'll save that for the next issue
=> stop-gap fix for mislabled fields

docs/integrations/amazon-eks/eks.mdx, docs/integrations/argocd/apiops.mdx, docs/integrations/azure-ad/k8s.mdx, docs/integrations/azure-aks/k8s.mdx, docs/integrations/consul/k8s.mdx, docs/integrations/google-gke/google-kubernetes-engine.mdx, docs/integrations/linkerd/k8s.md, docs/integrations/microk8s/k8s.mdx, docs/integrations/rafay/k8s.mdx, docs/integrations/vcluster/k8s.md, docs/k8s/developer-guide/releasing.md, docs/using-ngrok-with/k8s.md, examples/k8s/install-gateway-api.mdx, examples/k8s/install-ingress.mdx
We are moving to our new helm chart repo, charts.ngrok.com
=> chore: Update helm repo location

docs/getting-started/index.mdx
Given that our ideal audience for Office Hours is folks who have recently started with ngrok, this doc feels like the perfect place to plant the seed of another place where they can get some help.
=> Add tip+link to Office Hours from quickstart

docs/agent/config/v3.mdx
Improves the description and updates the table to include the correct values and missing description.
=> fix: upstream.protocol description for config v3

CONTRIBUTING.md, docs/agent/cli.mdx, docs/agent/diagnose.mdx, docs/agent/index.mdx, docs/guides/other-guides/running-behind-firewalls.md, sidebars.js
Preview: https://ngrok-docs-git-jen-diagnose-ngrok-dev.vercel.app/docs/agent/diagnose/
closes https://github.com/ngrok/ngrok-docs/issues/990
=> More `ngrok diagnose` docs

docs/agent/cli.mdx
Resolves ngrok-private/ngrok#33866
Updating ngrok TCP for --url flag and examples.
=> Update cli.mdx to udpate TCP examples

docs/guides/site-to-site-connectivity/end-customers.mdx, docs/guides/site-to-site-connectivity/index.mdx
This PR adds what we've been lovingly calling the ***CCG*** as a new guide in the existing site-to-site connectivity category.
=> Add guide: Site-to-site installation guide for end customers

docs/whats-new.mdx
=> feat: updating whats new

docs/using-ngrok-with/wordpress.md
latest wordpress release doesn't require any of the custom editing to work with ngrok.
=> fix: update wordpress docs

docs/getting-started/index.mdx, docs/guides/developer-preview/getting-started.mdx, docs/traffic-policy/variables/index.mdx, docs/traffic-policy/variables/ip-intel.mdx, traffic-policy/variables/conn.ip-intel.categories.mdx, traffic-policy/variables/conn.ip-intel.mdx
=> feat: adding IP intel docs

docs/agent/changelog.md
adding a missing changelog entry
=> fix: adding changelog entry for 3.14.1

traffic-policy/variables/conn.ip-intel.categories.mdx, traffic-policy/variables/conn.ip-intel.mdx
- updated the categories
- alphabetized the categories
- added the new categories
- added a blurb about the hierarchy
=> feat: updating the categories and adding new sources

docs/k8s/user-guide.mdx
Saw a small spelling error when following docs so here's the fix. Happy Holidays!
=> fix small spelling error

docs/whats-new.mdx
@S3Prototype Feel free to manipulate these as you see fit if you think different formatting/verbiage makes more sense for this page. These are just copy-pasted from the newsletter *changelog* section I showed you earlier today.
=> Add items from newsletter changelog to what's new

docs/agent/changelog.md
=> fix(changelog): typo 3.18 -> 3.19

docs/errors/err_ngrok_4100.mdx
Guidance for this error page was vague so I added the password reset link.
=> Adding password reset link to error page

docs/guides/device-gateway/arm64.md
Correct the file name (amd64.tgz -> arm64.tgz)
=> Update arm64.md: Correct the file name

src/components/code-block.tsx
https://ngrok.slack.com/archives/C03LRGNSG6A/p1738164861031989
=> code block: do not collapse long code snippets by default

docs/agent/changelog.md, docs/agent/version-support-policy.mdx, docs/whats-new.mdx
This just adds the notes, etc. for 3.20.0.
=> Release agent 3.20.0

traffic-policy/actions/jwt-validation/behavior.mdx, traffic-policy/actions/jwt-validation/config.mdx
First pass on updates to JWT validation docs
=> Document recommended inclusion of kid claim on incoming tokens and in JWKS document

docs/pricing-limits/index.mdx, shared/limits/free-resources.mdx
Relevant slack thread:
- https://ngrok.slack.com/archives/C01CYSSHVFS/p1742254516935579
=> Add Traffic Policy rules per plan to docs

docs/iam/rbac.mdx
See diff, removing duplicated word in text copy.
=> Remove duplicated word in RBAC docs

traffic-policy/actions/set-vars/examples/basic-example.mdx
=> fix: remove $ from set-vars expression

docs/traffic-policy/getting-started/agent-endpoints/cli.mdx, docs/traffic-policy/getting-started/agent-endpoints/config-file.mdx, docs/traffic-policy/getting-started/cloud-endpoints/api.mdx
=> Fix grammar

.gitignore, README.md
Add paragraph to README explaining how to these docs with a single command. Using Docker also isolates developers' machines from any malicious JS libraries and prevents any clutter on your host environment.
=> Explain how to run documentation in one line, using Docker

docs/pricing-limits/index.mdx
https://linear.app/ngrok/issue/DOC-61/update-simultaneous-tunnels-limits
=> Adding a row in pricing table for concurrent tunnel sessions

src/css/custom.css
=> css: update ketch css to be theme aware

biome.jsonc, package.json, pnpm-lock.yaml, src/components/ActionHub.tsx, src/components/ConfigExample.tsx, src/components/ConfigTable.tsx, src/components/ErrorDetails.tsx, src/components/IntegrationPageList.tsx, src/components/IntegrationsList.tsx, src/components/LangSwitcher/index.tsx, src/components/LangSwitcher/utils.ts, src/components/NgrokCard.tsx, src/components/RemoteMarkdownEmbedder.tsx, src/components/RemoteYamlBlock.tsx, src/components/search-params-endpoint-url.tsx, src/css/custom.css, src/css/tailwind-preflight-lite.css, src/plugins/ngrok-parse-integrations.js, src/theme/DocBreadcrumbs/index.tsx, src/theme/DocsRoot/index.tsx, src/theme/MDXComponents/Img/index.tsx, src/theme/Navbar/ColorModeToggle/index.tsx, src/theme/SearchBar/index.tsx, static/scripts/anchor-scroll-to.js, static/scripts/fix-redirect.js, static/scripts/ketch.js, static/scripts/prevent-fouc.js
prettier is really, really slow
biome lints AND formats the whole repo in ~200ms
=> swap prettier out for biome (gotta go fast)

traffic-policy/getting-started/GettingStarted.tsx
=> fix: broken traffic-policy example on getting-started

docs/guides/device-gateway/agent.md, docs/guides/device-gateway/agent.mdx
Update device gw guide (APIs on Devices) to new blog post content: 
https://ngrok.com/blog-post/secure-industrial-iot-connectivity
@S3Prototype to make changes to wording, formatting to match docs style
Purpose: Device gw guides are out of date and do not reflect newer features (cloud/internal endpoints and TP)
=> Updated device gw guide to recent blog post

docs/k8s/installation/install.mdx, docs/k8s/installation/update.mdx, docs/k8s/releasing.mdx
bumps the referenced versions of the operator everywhere from 0.17x to 0.18x
=> bump referenced operator versions

docs/overview/index.mdx
Corrects a minor spelling issue
=> Minor spelling fix - 'uning' -> 'using'

docs/universal-gateway/endpoint-pooling.mdx
=> Update message on endpoint pooling to point to Early Access page

traffic-policy/actions/owasp-crs-request/config.mdx, traffic-policy/actions/owasp-crs-response/config.mdx
Just added defaults for process_body.
=> Minor edits

docs/universal-gateway/endpoint-pooling.mdx, docusaurus.config.ts, src/components/youtube-embed.tsx, src/plugins/webpack-aliases.ts, tsconfig.json
Pretty self-explanatory!
Not sure if this is the right implementation or the best spot, but it felt natural to me.
=> Add video to Endpoint Pooling doc

docs/getting-started/_secure-your-app.mdx, docs/traffic-policy/actions/index.mdx
Noticed a few typos and some inconsistent sentence structure on this page while browsing the docs.
=> Copyedit Traffic Policy Actions overview page

docs/getting-started/kubernetes/ingress.mdx
Fix typo in Kubernetes ingress getting started guide
=> Fix tinyllama typo

docs/pricing-limits/index.mdx
https://linear.app/ngrok/issue/DOC-229/add-paygo-billing-info-to-pricing-page
=> Adding some FAQ's for PayGo plans to the pricing docs page 

docs/universal-gateway/examples.mdx, docs/universal-gateway/examples/lock-admin-dashboards.mdx, docs/universal-gateway/examples/route-api-app-traffic-user-agent.mdx, docs/universal-gateway/examples/snippets/_back-to-examples.mdx
Plus, add the `<Back />` component in a few places where I forgot them before.
=> Example gallery: Add a few links to the landing page to submit user-generated examples

docs/faq/faq.mdx
Per interlock conversation and conversation with CBC:
https://linear.app/ngrok/issue/DOC-339/equinox-faqs
[slack thread](https://ngrok.slack.com/archives/C032YNW4PB7/p1750441530500179)
=> Adding equinox faqs to docs

docs/universal-gateway/examples.mdx, docs/universal-gateway/examples/front-door-pattern.mdx, docs/universal-gateway/examples/rewrite-headers-redirects.mdx
To support the Shinobi case study/blog post!
=> Add site-to-site+rewrite example to the gallery

src/components/Definition/data.ts
quick win - alphabetize the entries in `data.ts` to make it easier to skim through and check if a term has been defined already.
=> Alphabetize Definition tooltip data

docs/integrations/airship/webhooks.mdx
Testing the content before i apply it to all the integration guides.
=> fix: update the traffic inspector section of airship

docs/universal-gateway/examples.mdx, docs/universal-gateway/examples/combine-auth-methods.mdx
This example is based on a customer who wants to accept traffic that's authenticated via IP restrictions `OR` JWT validation. This is a much more complicated example to explain that most of what's here so far, so happy to get any feedback on how to make the human readable **What's happening here** part any clearer.
=> New example: Combine Authentication Methods

docs/guides/identity-aware-proxy/securing-with-oauth.md, examples/ssh/http-oauth-authn.mdx
updates some of the areas we talk about the --oauth flag and changes it to use policy.
=> fix: updating oauth guides to use policy

docs/errors/details/_err_ngrok_3200.md, docs/errors/err_ngrok_3200.mdx
preview: https://ngrok-docs-git-jen-err-3200-ngrok-dev.vercel.app/docs/errors/err_ngrok_3200/
- fewer words
- follows this template: https://linear.app/ngrok/document/templates-for-cs-content-0ff5cb649a7f
=> update err 3200 page

docs/universal-gateway/examples.mdx, docs/universal-gateway/examples/blue-green-deployments.mdx, docs/universal-gateway/examples/canary-deployments.mdx
Fairly self-explanatory! Also doing some tweaks to the sidebar ordering to promote these over Minecraft (sorry, Minecraft).
=> New examples: canary and blue-green deployments

package.json, pnpm-lock.yaml, postcss.config.js, src/css/custom.css, src/css/tailwind-preflight-lite.css, src/plugins/tailwindcss.js, src/theme/Navbar/ColorModeToggle/index.tsx, tailwind.config.ts
This reverts commit 739ce73be3d004cbcedcc1376f219a71af4b72ad.
I merged it prematurely
=> Revert "[wip] update dependencies to use mantle with tailwind v4 (#1522)"

docs/whats-new.mdx
Updates What's New for recently shipped projects that missed getting updated here.
=> Update "What's New?" for BMG ships

docs/universal-gateway/examples/multiplex.mdx
https://ngrok.slack.com/archives/C057JDH5717/p1755631653921189
=> Adding some additional context for this example

docs/traffic-policy/actions/oauth.mdx, docs/universal-gateway/examples.mdx, docs/universal-gateway/examples/database-gateway.mdx, docs/universal-gateway/examples/webhook-gateway.mdx
Inspired by https://ngrok.com/blog-post/api-gateway-shapes-patterns-2025
=> Add two new gateway shapes: webhook gateway and database gateway

docs/traffic-policy/secrets.mdx
Provides an x-link from conceptual docs to ref docs
=> (Vaults, Secrets) X-link API Reference to Conceptual

docs.json, traffic-policy/macros/index.mdx
- Macros
- Secrets
becomes
**Macros**
- Macros Reference
- Secrets
=> Add sidebar header for Macros section

agent/version-support-policy.mdx, traffic-policy/concepts/index.mdx
Typo from https://github.com/ngrok/ngrok-docs/pull/1600
=> Correct typo for 3.30 agent release

docs.json
Mentioned here 
- https://ngrok.slack.com/archives/C03LRGNSG6A/p1759437811407699?thread_ts=1759437727.854079&cid=C03LRGNSG6A
=> Add missing  redirect
