- docs/ngrok-agent/config.md
`verify` is not a valid command for `ngrok config`. This change updates the documentation to reference `ngrok config check`, which is a valid command that returns the location of the configuration file.
> Fix command for checking location of configuration file

- docs/overview.md
The capital P in WordPress is important enough that a [function](https://developer.wordpress.org/reference/functions/capital_p_dangit/) is created to correct this error in WordPress sites.
> WordPress uses a capital P

- docs/api/resources/examples/_credentials_create_request.md
The request is required to be a POST but this seems to be missing from the example use of `curl`.
> Fix create credential request example

- docs/ngrok-agent/config.md
- docusaurus.config.js
Adds a trailing slash to our docs urls in the sitemap and when navigating to avoid a 302 redirect.
> fix: adding trailing slash

- docs/ngrok-agent/changelog.md
Overlooked in my original review: https://github.com/ngrok/ngrok-docs/pull/229#discussion_r1134682061. We also had to edit this to 3.2.1 anyhow because of some release funkiness with unique version numbers across channels.
> update changelog to 3.2.1

- docs/overview.mdx
Instead of pointing to the ngrok used for ssh page, point users to the reverse tunnel docs page.
> fix: point to ssh reverse tunnel page

- docs/using-ngrok-with/rust.md
It's missing from the `cargo add` section, and we can just use the std
Error type anyway.
> use-with-rust: drop anyhow dependency from example

- docs/api/index.md
answers the question: what timezone are the timestamps in for the api.
> fix: adding a note about timestamps

- docusaurus.config.js
- package.json
- pnpm-lock.yaml
- src/css/custom.css
- static/scripts/ketch.js
- adds `<meta name="ketch-tag-id">` tag to head
- flexes content based on `NODE_ENV`
- adds init script to `<head>`
- reads which tag we should use based on `<meta name="ketch-tag-id">` ☝️ 
- adds footer link to ngrok.com/privacy-preferences which allows users to configure their cookie consent preferences via ketch
- docusaurus.config.js was formatted by prettier (we should probably add that as a dep and CI step to this repo 😉 )
- adds global css to minimize the size of the ketch banner
> adds ketch (cookie consent) to ngrok docs

- src/css/custom.css
> ketch: reduce block padding on action buttons in the consent banner

- .gitignore
- docs/events/event-sources.mdx
Adding new documented fields for account_id and principal in event envelopes.
Screenshots:
> events: add account_id and principal information

- docs/ngrok-agent/changelog.md
Release notes for agent v3.3.0!
Depends on https://github.com/ngrok/ngrok-docs/pull/320 as that has documentation relevant to changes made in the latest agent version.
> release agent v3.3.0

- docs/using-ngrok-with.md
- docs/using-ngrok-with/django.md
- docs/using-ngrok-with/flask.md
- docs/using-ngrok-with/node-js.md
- docs/using-ngrok-with/python.md
- docs/using-ngrok-with/rust.md
It was decided to rename these repos, reflecting the change in the docs.
> ngrok-rust, ngrok-nodejs and ngrok-python naming

- docs/cloud-edge/modules/oauth/index.md
Small fix. The documentation has the returned header listed as `ngrok-auth-email`, but it is actually `ngrok-auth-user-email`.
> fix: documentation for oauth headers

- docs/using-ngrok-with/k8s.md
Changes the using-ngrok-with k8s page to mention static subdomains and removes the pro account from requirements.
> feat: update k8s documentation to mention static subdomains

- docs/cloud-edge/modules/mutual-tls.md
This commit refactors the mTLS documentation to improve it with:
- Example usage in each of the SDKs, the Agent CLI, config file, Kubernetes Ingress controller and Edges.
- Upstream header behavior
- Validation of certificate basic constraints
- Usage and behavior with multiple CAs
- Error condition behaviors
- Which plans it is available on
- A simple example of how to try it out with curl
- The fields that are populated in the http_request_complete.v0 event when mTLS is enabled
> refactor mTLS documentation

- docs/errors/index.md
- docs/errors/reference.md
- sidebars.js
this updates the errors section of the documentation to have the same structure as Events and API with two separate pages: Overview and Reference. consistency in how each documentation section is organized makes it easier for developers to find what they're looking for
i improved the copy a little bit as well while i was in here
> split out the errors reference into its own page, clean up copy

- docs/cloud-edge/modules/compression.md
- docs/cloud-edge/modules/ip-restrictions.md
- docs/cloud-edge/modules/mutual-tls.md
i made a few other small changes as part of this commit:
- the kubernetes ingress example for ip restrictions was expanded to include the ingress object
- standardized on the organization of the module documentation (a `reference` section which always contains "errors", "upstream headers", "events" and "licensing" and then a `behavior` section which has module-specific topics). shuffling this around makes the diff look messier than it actually is
> refactor compression module docs.

- docs/secure-tunnels/ngrok-agent/reference/config.md
The example mentions region under labels which causes confusion for new users thinking that setting region in the label will affect the agent region.
> chore(config.md): use env=prod instead of region

- docs/cloud-edge/modules/circuit-breaker.md
- docs/cloud-edge/modules/compression.md
- docs/cloud-edge/modules/ip-restrictions.md
- docs/cloud-edge/modules/mutual-tls.md
- docs/cloud-edge/modules/webhook-verification.md
adds and SSH section to each module's docs page
fixes a couple other bugs including:
- the ip restrictions agent CLI flags were wrong
- the headers section of the ip restrction docs page incorrectly said it was about the compression module
- update compression agent cli docs to put the port first like other module docs do
- consolidate terminology of webhook verification section from 'preflight verification' and 'one-time verification' to 'endpoint verification' which is more accurate
> add SSH commands, fix other bugs

- docs/api/index.md
Fixes broken link on the APIs page to agent sdks
> fix(api): fix broken agent sdk link

- docs/secure-tunnels/agentless.md
This adds the list of agent libraries along with a warning about some being in-development to bring more exposure to the libraries. In addition it breaks out the guides into it's own section.
> feat(agentless): Add list of agent libraries

- docusaurus.config.js
google tag manager seemed to be missing from the docs pages. this adds it. also, GA tracking is managed via tag manager, so we don't need that anymore.
> feat: add gtm to docs pages

- docs/cloud-edge/modules/circuit-breaker.md
- docs/cloud-edge/modules/compression.md
- docs/cloud-edge/modules/ip-restrictions.md
- docs/cloud-edge/modules/mutual-tls.md
- docs/cloud-edge/modules/openid-connect.md
- docs/cloud-edge/modules/webhook-verification.md
- docs/events/index.mdx
There are no meaningful changes in this changeset, it just moves around sections and text in the docs of existing modules to match the new format used by the docs for request/response headers and the oauth modules.
It also adds syntax highlighting to existing examples + normalizes how we display variables that need to be added by the user in example code.
> Reorganize existing modules to match new format.

- docs/cloud-edge/modules/circuit-breaker.md
We have it right in the other integration pages and I noticed the error when trying to copy/paste this into a new moduleset I was making.
> fix: module set circuit breaker documentation

- docs/secure-tunnels/ngrok-agent/reference/config.md
This PR also adds the `us-cal-1` region information as well as updates the existing `us` region information.
> fix(agent-config): add missing information about addr and schemes

- docs/using-ngrok-with/go.md
This update adds a link to How to Set Up a Custom Domain documentation to help users know about the feature.
> add custom domain link to go lib docs

- src/css/custom.css
This PR modifies our font declarations to properly map to our font weights. Currently, we don't map Euclid Semibold to the `600` weight. This causes browsers to render a faux bold which affects readability. This PR fixes that by spec'ing those weights to a single `EuclidSquare` font name, and changing font files per weight.
In the overview, you'll see lots of faux bold fonts get changed to a real semibold. You'll notice the top menu also got a little thicker, since it was intended to be the "medium" font weight. Now it's actually rendered as such.
> Correctly map custom font weights

- src/css/custom.css
We were only applying our text color to the paragraph element. This spec's that color on the entire markdown body, and then applies a darker color to headers only. This should solve the issue of lists and tables have darker text than paragraphs.
> Markdown text colors

- src/css/custom.css
This is a follow up from #433 to improve the initial load. This specifies a sans-serif font stack which is less jarring on initial load than Times New Roman. It also removes the redundant font declaration from headings, since those inherit from the base font family.
https://github.com/ngrok/ngrok-docs/assets/1369864/7ac0102e-0cc4-4c7c-81a1-4be4a8341a70
https://github.com/ngrok/ngrok-docs/assets/1369864/154af2ea-e2a4-463e-9c58-eb3000e45b5d
You can scrub through the attached videos to see the improvement here. Before, it'd flash Times New Roman and have much more layout jumps.
> Font refinements

- docs/using-ngrok-with/k8s.md
We've gotten a lot of feedback that it is not clear you must register the domain through the dashboard. This PR makes it so that is required step before you get to setting the domain field and explains to the user they will need it later.
> chore(k8s): make registering a domain an explicit step

- docusaurus.config.js
- package.json
- pnpm-lock.yaml
- postcss.config.js
- src/components/IntegrationPageList.tsx
- src/components/IntegrationsList.tsx
- src/components/NgrokCard.tsx
- src/components/integrations/schema.ts
- src/components/integrations/use-integrations.tsx
- src/css/custom.css
- src/plugins/tailwindcss.js
- tailwind.config.js
Make integration page data loading safer and simplify rendering logic
- adds tailwind support
- uses zod for defining the integration schemas and type safe parsing
- simplifies the rendering logic in integration pages (use css for layout, not confusing js methods with `:any` sprinkled everywhere)
shortcut: https://ngrok-docs-git-cody-fix-integration-page-list-ngrok-dev.vercel.app/docs/integrations
> Improve integrations

- docs/agent/index.mdx
The original text said "When you provision a new authtoken, the full token is only once.", which is an incomplete sentence. Updated the sentence to indicate that it is displayed once.
> Fixing minor typo in Authtoken section

- docs/agent/config.mdx
The `domain` and `protocol` don't go along with the `labels`, so the doc better reflect that
See discussion in https://github.com/ngrok/ngrok-docs/issues/481
> Update config.mdx with tip about labels and domains

- docs/agent-sdks/index.mdx
We updated the JS SDK from ngrok-nodejs to ngrok-javascript. Updating the links since docs link did not forward and was broken.
> Update JS SDK links

- src/css/custom.css
Closes #491. Follow up question though, the page has `<meta charset="utf-8">` set, so it's odd to me that this would show up as weird characters. Hmm!
> Arrows hotfix

- docs/http/request-headers.mdx
- docs/http/response-headers.mdx
- docs/network-edge/index.mdx
Fixed all the split infinitives in Docs
> Fixing all the split infinitives in Docs

- docs/integrations/contentful/webhooks.mdx
This pull request updates the documentation for using ngrok to verify signed Contentful webhook requests at the edge. These updates improve the overall ngrok + contentful webhook documentation and make callouts about signed webhook verification where appropriate.
cc: @russorat
> feat: updates contentful webhooks documentation to include information about webhook request verification []

- docs/network-edge/gslb.mdx
- examples/agent-cli/tcp-fixed.mdx
- examples/agent-config/tcp-fixed.mdx
Now folks don't need to care about regions for TCP tunnels!
See https://github.com/ngrok-private/ngrok/issues/23493
> tcp tunnels: region is no longer required with the advent of cross-region tcp tunnels

- examples/agent-cli/http-schemes.mdx
The additional option for selecting what schemes to forward on is `--scheme` not `--schemes`
> Update typo for the usage of the CLI `ngrok http` command 

- docs/agent/ssh-reverse-tunnel-agent.mdx
Mention `id_ed25519.pub` since that is the ssh default now.
> add ~/.ssh/id_ed25519.pub to ssh-reverse-tunnel-agent

- README.md
- docs/agent/api.md
- docs/agent/changelog.md
- docs/agent/cli.mdx
- docs/agent/config.mdx
- docs/agent/index.mdx
- docs/errors/details/_err_ngrok_8012.md
- docs/guides/getting-started.mdx
- docs/guides/running-behind-firewalls.md
- docs/guides/upgrade-v2-v3.mdx
- docs/integrations/tiktok/webhooks.mdx
- docs/obs/index.mdx
- docs/using-ngrok-with/rdp.md
- docs/using-ngrok-with/ssh.md
indented code blocks don't render correctly now (since all `.md` and `.mdx` are parsed w/ mdx)
https://mdxjs.com/docs/what-is-mdx/#markdown
> batch of formatting fixes (missed in docusaurus v3 upgrade)

- docs/agent/cli.mdx
- docs/http/index.mdx
- package.json
Two sections of the docs are being updated to make note of the new HTTP/2 support for upstream services.
> Add instructions for HTTP/2 support

- docs/using-ngrok-with/django.md
- docs/using-ngrok-with/flask.md
- docs/using-ngrok-with/java.md
- docs/using-ngrok-with/node-js.md
- docs/using-ngrok-with/python.md
Move the SDK's up to top position, remove outdated alpha/beta notes, add links for java.
> Update mentions of sdk's on using-ngrok-with pages

- docs/http/oauth.mdx
- docs/integrations/github/oauth.mdx
I believe this is due to ngrok requiring an email for login and requesting that scope during the OAuth handshake.
> Add limitation for GitHub OAuth

- docs/integrations/linkerd/index.mdx
Fixes an issue with #543, in which I'd forgotten to change the `TK` (to come) in the integration hub copy.
> Add missing Linkerd integration hub copy

- flake.lock
When using nix, I noticed warnings about unsupported engine
https://github.com/ngrok/ngrok-docs/blob/fcc89a2d2f6bbdbeb14c44984b8f0175b64e7d14/package.json#L6-L8
I ran `nix flake update` to update the version of nixpkgs we are using which now puts us on node 20.10.0.
> Update flake.lock so node version is compatible with package.json

- docs/integrations/linkerd/k8s.md
- docs/integrations/rancher/k8s.md
- docs/integrations/vcluster/k8s.md
In the process of writing my latest integration how-to for AKS, I was referencing past pieces I'd written and noticed a number of formatting errors that hurt readability. The Rancher how-to also had a lengthy YAML with the indentation all messed up, which made me wonder if one could actually duplicate the step.
I also made some small QOL fixes, like changing references from `...ngrok-free.app` to `ngrok.app`.
> Fix formatting in recent integration how-to guides

- docs/integrations/spectro-cloud/index.mdx
I mis-configured the Integrations Hub frontmatter in #575, which meant the page didn't show associated how-to guide. This PR should fix that.
> Fix Integrations Hub page for Spectro Cloud

- docs/agent/changelog.md
- Added `--policy-file` flag that accepts Traffic Policy configuration for [HTTP](/http/traffic-policy/), [TCP](/tcp/traffic-policy/), or [TLS](/tls/traffic-policy/) traffic.
- Added support for `policy` field in [agent config](/http/traffic-policy/?cty=agent-config) for Traffic Policy configuration.
> docs(agent): changelog for 3.6.0

- docs/getting-started/index.mdx
These pages can detect platform and have explicit directions which include the account's authtoken.
> Adding links to the setup and installation pages in the dashboard

- docs/http/traffic-policy/gallery.mdx
This needs quoting, otherwise you get the following error:
```
ERROR:  failed to start tunnel: Invalid policy expression.
ERROR:  ERROR: <input>:1:2: undeclared reference to 'getDate' (in container '')
ERROR:   | (getDate != 1)
ERROR:   | .^.
```
Unless I did something wrong!
> Fix policy gallery for GETs only

- examples/java-sdk/http-basic-auth.mdx
- examples/java-sdk/http-branded-domain.mdx
- examples/java-sdk/http-circuit-breaker.mdx
- examples/java-sdk/http-compression.mdx
- examples/java-sdk/http-fileserver-abs-path.mdx
- examples/java-sdk/http-fileserver-windows.mdx
- examples/java-sdk/http-fileserver-working-dir.mdx
- examples/java-sdk/http-ip-restrictions.mdx
- examples/java-sdk/http-oauth-authn.mdx
- examples/java-sdk/http-oauth-authz.mdx
- examples/java-sdk/http-oauth-byo-app.mdx
- examples/java-sdk/http-oauth-customize-scopes.mdx
- examples/java-sdk/http-random.mdx
- examples/java-sdk/http-schemes.mdx
- examples/java-sdk/http-static-domain.mdx
- examples/java-sdk/http-webhook-verification.mdx
- examples/java-sdk/http-websocket-tcp-converter.mdx
- examples/java-sdk/http-wildcard-domain.mdx
Adding HTTP examples for ngrok-java. This is only adding the examples to the `examples` folder, not including them in the docs. This PR is a blocker for https://github.com/ngrok/ngrok-docs/pull/616
> Adding HTTP examples for ngrok-java

- docs/getting-started/index.mdx
- docs/guides/getting-started.mdx
`apt-key` and `/etc/apt/trusted.gpg.d` are deprecated due to security concerns.  the new recommended method is to directly reference the key in the repository declaration.
one possible issue users could run into is if the `/etc/apt/keyrings` directory is not already created, but it's an easy enough fix.
some references for the deprecation and changes:
- https://wiki.debian.org/DebianRepository/UseThirdParty
- https://www.linuxuprising.com/2021/01/apt-key-is-deprecated-how-to-add.html
- https://askubuntu.com/questions/1286545/what-commands-exactly-should-replace-the-deprecated-apt-key?newreg=c7d51f5afac945fea79db7a504d68e76
> use updated method of signing repos

- examples/agent-cli/http-traffic-policy.mdx
- examples/agent-config/http-traffic-policy.mdx
- examples/go-sdk/http-traffic-policy.mdx
- examples/javascript-sdk/http-traffic-policy.mdx
- examples/k8s/http-traffic-policy.mdx
- examples/python-sdk/http-traffic-policy.mdx
Two things were broken in the example:
-  The `content_type` attribute seems to have been removed in favor of `headers` with `content-type`. I think I got that fixed correctly off of everything.
- The `log` example was out of order and broken. It's also not present in all examples, so I just took it out.
I confirmed the change to the agent config. I haven't and probably don't have time to test _all_ of the others.
> Fix and consolidate the intro Policy examples

- docs/integrations/contentful/webhooks.mdx
Removes a note about product tiers for Contentful Webhook Request Verification. This feature will be accessible to all Contentful customers.
> refactor: remove mention of product tier for Contentful WRV

- docs/http/traffic-policy/actions/index.mdx
Update to indicate we are adding headers `to` the request or response rather than `from` the request or response
> Fix the wording on Add Headers

- docs/using-ngrok-with/flask.md
This directly links to the configuration variables in the docs. The link to the stackoverflow post was changed, so I added it directly.
> Fix the links in flask.md

- static/scripts/fix-redirect.js
This fixes issues like our blog post that redirects to an old page with no sidebar and out-dated information to a newer page with the correct information. This also covers the other parts of the page.
> Redirect User Management to new IAM pages

- docs/errors/details/_err_ngrok_9009.md
- docs/using-ngrok-with.md
- docs/using-ngrok-with/openvpn.md
- docs/using-ngrok-with/wordpress.md
from: https://github.com/inconshreveable/ngrok/issues/694
> fix: adding info about url scheme missing

- docs/k8s/crds.md
- docs/k8s/user-guide.mdx
Updates the guide with initial section for the traffic policy docs
> update guide with traffic policy

- docs/integrations/linode/gslb.mdx
Globally was spelled incorreclty.
> Fixed a typo in the metadata

- docs/agent/changelog.md
and the port 80 as multiple customers confused and are setting domain with 443.
> Update changelog.md to include port 80 for CRL address change

- docs/api/resources/edge-route-policy-module.mdx
- docs/http/traffic-policy/index.mdx
- docs/k8s/user-guide.mdx
- docs/tcp/traffic-policy/index.mdx
- docs/tls/traffic-policy/index.mdx
- shared/warnings/traffic-policy-preview.mdx
We've already pushed a number of breaking changes to how we parse policy documents, and it wasn't clear to me from the existing docs that we don't intend backwards compatibility yet, so add notes to that effect.
> Indicate 'traffic policy' is in preview and may have breaking changes

- examples/javascript-sdk/http-traffic-policy.mdx
- examples/python-sdk/http-traffic-policy.mdx
After spending too much time debugging my `yaml` config and then learning we don't support it yet for the SKDs, I'm adding a note so no one else repeats this.
> Clarify that only json policy configuration is currently supported

- docs/agent/cli.mdx
- examples/agent-cli/http-traffic-policy.mdx
- examples/agent-cli/tcp-traffic-policy.mdx
- examples/agent-cli/tls-traffic-policy.mdx
Resolves ngrok-private/ngrok#31125
The docs updates to go with these changes:
- [policy](https://github.com/ngrok-private/ngrok/pull/31060)
- [agent](https://github.com/ngrok-private/ngrok/pull/31101/files)
(To be deployed **after** PRS are merged and go live with thursday's agent release)
> update docs with renamed flags

- docs/guides/device-gateway/agent.md
- docs/guides/device-gateway/index.md
Removed site-to-site terminology from device guide.
> Remove site-to-site terminology from devices guide and index

- examples/agent-config/http-traffic-policy.mdx
- examples/agent-config/tcp-traffic-policy.mdx
- examples/agent-config/tls-traffic-policy.mdx
I noticed that after #862, some instances of example config files were changed from `policy` to `traffic_policy`, but that hadn't reached the Traffic Policy-specific doc ([example for HTTP](https://ngrok.com/docs/http/traffic-policy/?cty=agent-config)) for each type of endpoint.
This PR updates those three examples to update the naming. And fixes what I believe to be malformed indentation in the TCP example.
> Update policy to traffic_policy on HTTP/TLS/TCP 

- docs/k8s/crds.md
Replace the embedded struct ngrokApiCommon with the actual properties it provides on the resources.
> fix: Update docs for kubernetes CRDs

- docs/agent/config.mdx
Many users copy and paste the full example blindly into their configuration file which leads to issues. This change converts the full example into a fully documented configuration file similar to other tools which should lead to forcing users to read each section before enabling functionality. In addition to this, there are numerous improvements which include linking to configuration fields for tunnels, including links to dashboard for obtaining tokens and keys, etc.
> Turn Full Example Config into a Fully Documented Default Configuration File

- docs/guides/device-gateway/agent.md
- docs/guides/site-to-site-apis-mtls/index.mdx
- docs/guides/site-to-site-dbs-mtls/index.mdx
Changed `client-crt.pem` to `server-crt.pem` in the three new guides that use mTLS. Also formatted a `201` that was missing backticks. Simple PR.
> Fix command to start tunnel with mTLS and add formatting

- docs/guides/device-gateway/sdk.md
I used `{TUNNEL_DOMAIN}` in the command to start the tunnel and `{YOUR_DOMAIN}` in the block about access the API. I updated it to use the correct variable.
> Correct variable name

- docs/network-edge/domains-and-tcp-addresses.mdx
From the product feedback interlock. I added a small section with an H3 including the word "apex" for discoverability. I got @justngrok's feedback that it meets our needs.
> Add section for domain apex

- .github/workflows/deploy.yml
We want to remove files that are in the remote but not source directory, so that we stop indexing old content. 
This is to test on dev. 
Docs: 
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/sync.html
> Add the delete flag to aws s3 sync

- .github/workflows/deploy.yml
We want to remove files that are in the remote but not source directory, so that we stop indexing old content.
Tested on dev, this is for stage and prod. 
Note: cleaning up dev took almost 2 hours of action run time, for both stage and prod we may see some timeouts on deploy. 
Docs:
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/sync.html
> Add the delete flag to remove old docs in stage and prod

- static/scripts/fix-redirect.js
Before this, going to https://ngrok.com/docs/network-edge/pops/ would redirect loop.
The reason for this is twofold:
1. The match should have been exact, since the redirect was a prefix of itself
2. The redirect check at the bottom checked href ('https://ngrok.com/docs/....') against a path ('/docs/') to see if they were the same, and so they never were.
This updates that check as well.
> fix: /docs/network-edge/pops redirect loop

- docs/guides/api-gateway/kubernetes.mdx
I could have explained this part of Step 2 better, and I moved to phase-based naming.
Also figured out the spacing issue in the prereqs section.
> Add small fixes to new API-G+k8s guide

- traffic-policy/variables/conn.mdx
This PR adds `conn.server_region` to the traffic policy connection variables. This allows users to look up what point of presence on ngrok serviced the connection for the current request.
> feat: adds conn.server_region variable to traffic policy docs

- traffic-policy/variables/conn-tcptls.mdx
Adds `conn.server_region` to the TCP / TLS endpoint traffic policy connection variables.
> feat: add conn.server_region to tcp / tls docs

- docs/guides/api-gateway/kubernetes.mdx
I didn't realize that the K8s Operator doesn't yet support phase-based naming, and while it's coming soon (https://github.com/ngrok/ngrok-operator/pull/456), I'd rather this work correctly right now and update it again in the future.
> API gateway guide: revert to `inbound`

- docs/tls/traffic-policy/expressions/variables.mdx
- examples/agent-config/tls-traffic-policy.mdx
These variables will no longer be available in the on_tcp_connect phase, which is all that's available to tls endpoints. I copied the example from TCP to remove reference to tls variables.
> restrict conn.tls vars to http phases

- docs/traffic-policy/index.mdx
- docs/traffic-policy/templates/index.mdx
- static/scripts/fix-redirect.js
Fixes the title of the templates section, adds redirects and fixes the overview page link.
> fix: Change templates title, fix links

- traffic-policy/actions/forward-internal/examples/1-basic-example.mdx
we use `on_http_request` now :)
> fix: inbound -> on_http_request for forward-internal example

- .github/workflows/deploy.yml
The `aws s3 sync --delete` we're using can conflict with itself if run in parallel.
Specifically, if one action is trying to deploy a new version of docs, and at the same time another action is trying to deploy a different, also new version of docs, they can race such that i.e. we get "index.html" from one, but "main.<hash>.js" from the other, and for `main.<hash>.js` from one to be deleted by the other run
In order to avoid that happening, add github's concurrency control to stop any previous runs before we start a new deploy.
At least, based on my reading of the github action docs, this should do what we want!
> Avoid running deploys in parallel

- docs/k8s/crds.md
- docs/k8s/user-guide.mdx
Adds CRD reference documentation and usage guides for the ngrok operator agent endpoints feature
> add k8s agent endpoint docs

- traffic-policy/actions/circuit-breaker/examples/basic-example.mdx
Was experimenting with the circuit breaker today for a blog post and noticed the config in the example fails because `tripped_duration` is set to `3m` when the maximum is `2m`:
```
ERROR:  failed to start tunnel: Failed to parse configuration for circuit-breaker: tripped_duration must be between 1s and 2m0s inclusive, was seconds:180.
```
> Fix error in circuit-breaker example config

- docs/whats-new.mdx
Adds a section for Traffic Policy macros to the What's New page
> Add Traffic Policy macros to the What's New page

- docs/integrations/amazon/oauth.mdx
- docs/traffic-policy/actions/oauth.mdx
- traffic-policy/actions/oauth/behavior.mdx
- traffic-policy/actions/oauth/config.mdx
> fix: oauth polish

- docs/guides/api-gateway/get-started.mdx
- docs/guides/other-guides/forwarding-and-load-balancing-with-cloud-endpoints.mdx
- docs/guides/other-guides/path-based-routing-and-policy-decentralization-with-cloud-endpoints.mdx
- docs/k8s/user-guide.mdx
- docs/network-edge/internal-endpoints.mdx
- traffic-policy/actions/forward-internal/config.mdx
- traffic-policy/actions/forward-internal/examples/1-basic-example.mdx
Slack discussion here:
- https://ngrok.slack.com/archives/C03LRGNSG6A/p1736525986652769
`binding: internal` is unnecessary, and we shouldn't document it anymore. This PR removes all references to `binding: internal` and `--binding internal` in CLI and Traffic Policy docs
> Remove references to binding internal throughout the docs

- docs/errors/details/_err_ngrok_1006.md
- docs/errors/details/_err_ngrok_107.md
- docs/errors/details/_err_ngrok_108.md
- docs/errors/details/_err_ngrok_3004.md
- docs/errors/details/_err_ngrok_305.md
- docs/errors/details/_err_ngrok_306.md
- docs/errors/details/_err_ngrok_314.md
- docs/errors/details/_err_ngrok_3200.md
- docs/errors/details/_err_ngrok_3208.md
- docs/errors/details/_err_ngrok_334.md
- docs/errors/details/_err_ngrok_354.md
- docs/errors/details/_err_ngrok_4000.md
- docs/errors/details/_err_ngrok_502.md
- docs/errors/details/_err_ngrok_702.md
- docs/errors/details/_err_ngrok_715.md
- docs/errors/details/_err_ngrok_717.md
- static/scripts/fix-redirect.js
We have broken links in the non-generated content in our error docs. This PR fixes them and adds redirects where necessary.
> Fix broken links in our error docs

- docs/guides/other-guides/how-to-set-up-a-custom-domain.md
Change spelling of "perfromed" to "performed" in how-to-set-up-a-custom-domain
> Fix one spelling issue

- docs/guides/other-guides/how-to-set-up-a-custom-domain.mdx
- docs/guides/other-guides/securing-your-tunnels.mdx
- docs/k8s/crds.mdx
I believe adding `title` to the frontmatter of a page will improve its search performance. This PR does so to a couple docs as a small test.
- "Custom domain" results in [the kubernetes guide](https://ngrok.com/docs/k8s/custom-domain/) first. The [second top-level result ](https://ngrok.com/docs/guides/other-guides/how-to-set-up-a-custom-domain/)is the preferred answer.
- "Secure" does not result in the "[Securing ngrok](https://ngrok.com/docs/guides/other-guides/securing-your-tunnels/)" guide
- "crd" does not result in [the CRDs page](https://ngrok.com/docs/k8s/crds/)
> Test if adding `title` to frontmatter improves search`

- src/components/search-params-endpoint-url.tsx
These are not used yet, but will be in an upcoming change to our error docs generation.
> add components to read endpoint url from search params

- sidebars.js
> Put agent cli back in the sideabar

- docs/traffic-policy/examples/index.mdx
During the interlock today I remembered that I had some sitting around to add here. I also started to use the new Mantle-based code editor—if no one else jumps on it, I can continue working on converting them in a separate PR.
> Add some new use cases to Traffic Policy examples

- docs/guides/api-gateway/get-started.mdx
- docs/traffic-policy/getting-started.mdx
- docs/traffic-policy/getting-started/agent-endpoints/cli.mdx
- docs/traffic-policy/getting-started/agent-endpoints/config-file.mdx
- docs/traffic-policy/getting-started/cloud-endpoints/api.mdx
- docs/traffic-policy/index.mdx
- static/scripts/fix-redirect.js
- [On this page in prod](https://ngrok.com/docs/traffic-policy/getting-started/agent-endpoints/cli/#step-3-test-it-out), when you click the link in "[examples, use-cases and guides](https://ngrok.com/docs/traffic-policy/examples/)," it takes you to a 404. This PR fixes that.
- This PR replaces links to `/traffic-policy/examples` as it doesn't exist
> Fix links/redirects to traffic policy examples

- src/components/IntegrationPageList.tsx
- src/components/integrations/schema.ts
I noticed earlier today that all the integrations pages are broken—the [integrations hub](https://ngrok.com/docs/integrations/) is empty, as are the individual hubs for each provider.
Error I'm seeing on any integrations page:
```
ZodError: [
{
"code": "invalid_type",
"expected": "string",
"received": "undefined",
"path": [
11,
"docs",
0,
"contentTitle"
],
"message": "Required"
}
]
```
I poked around a bit and figured that error was getting thrown because not every integrations guide explicitly has a `title:` in the frontmatter, and this Zod dude doesn't like an undefined required string. Making `contentTitle` optional _seems_ to fix the error and restore the integrations hubs... but at what cost?
> Potentially fix integrations pages

- docs/agent/ingress.mdx
- docs/guides/other-guides/securing-your-tunnels.mdx
Clarifies documentation to state that private key material from automatically provisioned certs is unavailable
> Docs: Clarify that automatically provisioned cert private key material is inaccessible

- docs/iam/sso.mdx
Fix for self-referential 'Next' button in footer.
Fixes: https://ngrok.com/docs/iam/sso/
> Fix for self-ref next link (SSO)

- docs/guides/api-gateway/multicloud.mdx
Just a small fix that didn't get translated into the doc after building/testing this locally.
> Add fix to multicloud API gateway guide routing

- docs/k8s/crds/boundendpoint.mdx
- docs/k8s/crds/domain.mdx
- docs/k8s/installation/install.mdx
- docs/universal-gateway/kubernetes-endpoints.mdx
- Fixes a couple broken links
- Adds more info to [the Kubernetes Endpoints page](https://ngrok-docs-git-shaquil-doc-227-update-k8s-docs-ngrok-dev.vercel.app/docs/universal-gateway/kubernetes-endpoints/#how-do-i-update-endpoint-selectors)
[Preview](https://ngrok-docs-git-shaquil-doc-227-update-k8s-docs-ngrok-dev.vercel.app/docs/universal-gateway/kubernetes-endpoints/#how-do-i-update-endpoint-selectors)
> Update K8s endpoint docs

- src/components/ConfigExample.tsx
- src/components/LangSwitcher/index.tsx
- src/components/LangSwitcher/utils.ts
There are pages with lots of `<LangSwitcher>` components, like [this page](https://ngrok.com/docs/traffic-policy/actions/restrict-ips/#restricting-access-with-allow-and-deny-lists), which uses a ton of `<ConfigExample>`s, which use `<LangSwitcher>` under the hood. These pages experience layout shift because when you change the language on one block, it changes the language on all the blocks, which cumulatively changes the size of the page drastically.
This makes code blocks in the langswitcher collapsible by default, with a shorter height than standard code blocks, to reduce overall layout shift. There's probably a better solution but this is good for now.
This also adds the ability to hide the agent config or traffic policy tabs from the `<ConfigExample>` component
> Fix lang switcher layout shift

- traffic-policy/actions/custom-response/examples/http-upstream-maintenance-page.mdx
- traffic-policy/actions/custom-response/examples/index.mdx
Preview: https://ngrok-docs-git-jen-add-example-ngrok-dev.vercel.app/docs/traffic-policy/actions/custom-response/#custom-response-for-internal-endpoint-downtime
> Adds example of custom-response for internal endpoint downtime

- package.json
- pnpm-lock.yaml
- src/components/code-block.tsx
Uses tabs instead of spaces in our code snippets, which should make indentation more consistent and prevent issues with using tools that don't expect tabs in YAML.
See [this linear](https://linear.app/ngrok/issue/EPD-629/code-blocks-in-docs-contain-tabs-for-indentation-which-dont-work-with) issue for more info.
If you want to test this, you can ensure that code snippets in this PR's preview are rendering the exact same as those in prod, as swapping from tabs to spaces should cause no issues there. Some examples:
- K8s docs
- [This PR](https://ngrok-docs-git-shaquil-doc-232-convert-tabs-to-87a271-ngrok-dev.vercel.app/docs/k8s/guides/how-to/rate-limiting/?kind=gateway-api#rate-limiting-examples)
- [Prod](https://ngrok.com/docs/k8s/guides/how-to/rate-limiting/?kind=gateway-api#rate-limiting-e …
> Convert codeblock spaces to tabs

- package.json
- pnpm-lock.yaml
- src/components/code-block.tsx
1. update dependencies + pnpm version
2. updates mantle: fixes an issue where the initial render of the code block would use unescaped html as dangerouslySetInnerHtml
1. all rendered lines now use spaces as indentation by default, no need to convert tabs
> update dependencies; remove need to convert tabs to spaces and that dep

- traffic-policy/variables/conn.tls.mdx
A companion to https://github.com/ngrok-private/ngrok/pull/36488
This change adds "JA4 fingerprint" as one of the "vars" available for use in the Traffic Policy.
> Add ja4 fingerprint to traffic policy docs

- package.json
- pnpm-lock.yaml
- src/components/code-block.tsx
this PR [updates mantle to 0.25.0](https://github.com/ngrok-oss/mantle/releases/tag/%40ngrok%2Fmantle%400.25.0) and allows the `CodeBlockCode` to support:
- auto indentation inference based on code language
- overrides of inferred indentation via the `indentation` prop
- parse meta string supports the `indentation="spaces|tabs"` prop
> update mantle: support auto indentation and overrides

- docs/universal-gateway/edges.mdx
We have a date of December 31st, 2025 for when we will sunset edges, as such we need to update the documentation to communicate this date to users.
> update: edges sunset date

- docs/iam/users.mdx
- src/components/Definition/data.ts
- src/components/Definition/index.tsx
This component adds a hovercard over technical terms. The hovercard tells the reader what the term means so they don't have to navigate away from the page to look it up.
- You can hover IP CIDR on [this page](https://ngrok-docs-git-shaquil-doc-246-add-a-learn-mor-9d9f8d-ngrok-dev.vercel.app/docs/iam/users#ip-restrictions)
- And you can hover over JIT provisioning and SCIM [on this page](https://ngrok-docs-git-shaquil-doc-246-add-a-learn-mor-9d9f8d-ngrok-dev.vercel.app/docs/iam/users#provisioning)
https://github.com/user-attachments/assets/597c04dc-2208-49c3-92d9-3ecce16f72aa
> Add a `<Definition>` component

- traffic-policy/actions/oidc/config.mdx
While reviewing the docs, noticed that the OIDC traffic policy action listed `scope` instead of the correct `scopes` field (an array of strings).
> fix(traffic-policy/oidc): rename config field 'scope' to 'scopes'

- src/theme/DocSidebarItem/Link/index.tsx
- src/theme/DocSidebarItem/Link/styles.module.css
Currently the sidebar doesn't show the page you're viewing, which forces you to scroll to where it is yourself. Very frustrating. This fixes that.
1. Open a page like the [TCP addresses docs](https://ngrok-docs-git-shaquil-doc-30-make-the-sidebar-27006a-ngrok-dev.vercel.app/docs/universal-gateway/tcp-addresses/#api)
2. Click a link, like the one that says "/reserved_addrs API Resource" in the first bullet point
3. Observe that the sidebar scrolls when you navigate to the page
> Make sidebar scroll to the page you're viewing

- src/components/LangSwitcher/index.tsx
- src/components/code-block.tsx
[Preview here](https://ngrok-docs-git-disable-show-more-in-code-blocks-ngrok-dev.vercel.app/docs/traffic-policy/actions/url-rewrite/#rewrite-using-regular-expressions)
We currently truncate code blocks and display a "Show more" button that allows users to expand the code if it's long:
This PR removes that functionality, as users has gotten confused by this and missed the "Show more" while scanning pages:
(Same example untruncated)
> Remove "show more" from code blocks

- docs/guides/other-guides/load-balancing-kubernetes.mdx
[#CON-135](https://linear.app/ngrok/issue/CON-135/how-to-pool-endpoints-with-k8s-operator)
This is a quick guide that explicitly walks through the process of setting up `AgentEndpoint`, Ingress, and Gateway API implementations for Endpoint Pooling.
In writing this I realized how useful a similar walkthrough would be for the use case at the very end—pooled internal Agent Endpoints in K8s—but I think that should be a separate guide, as it requires configuring cloud endpoints and Traffic Policy/`forward-internal`. Open to suggestions on that, though!
> Add new guide for load balancing between K8s services

- docs/agent-sdks/index.mdx
- docs/agent/index.mdx
- docs/api/index.mdx
- docs/errors/index.md
- docs/iam/index.mdx
- docs/obs/index.mdx
- docs/traffic-policy/index.mdx
- docs/universal-gateway/overview.mdx
I noticed this a long time ago, forgot about it, but then noticed it again today—the page titles for our **Overview** docs are all **Overview | ngrok Documentation**, which makes differentiating between them hard if you have multiple tabs open.
I decided to go ahead with this solution, but also open to suggestions on where/how we should specify on-page vs. sidebar vs. SEO titles. I think there's at least one other way we might do this.
Before:
After:
Good news, and potential side quest opportunity—looks like Google ignores page titles on search results, so this hasn't been an issue when people are searching for our docs on Google. But how/why does Google just ignore our titles and make its own?
> Update titles and sidebar labels to differentiate page titles for Overviews

- src/components/LangSwitcher/index.tsx
It's not perfect (we don't have size on mantle buttons, as far as I can tell, so I manually did it via tailwind classes).
Before:
After:
Designs:
> feat: improve padding and sizing of code language tabs

- docs/agent/config/v3.mdx
Addresses this issue:
- https://linear.app/ngrok/issue/SUP-113/whats-the-long-term-plan-for-tunnels-section-of-v3-config
We need to warn users that `tunnels` will not be available in the future.
> Warn users that `tunnels` will be removed from v3 eventually

- docs/getting-started/_secure-your-app.mdx
This existing rule doesn't work:
1. There's no closing `'` around the email address
2. The double `!` operators doesn't make sense and the first one errors because you're trying to `NOT` a string.
This change creates a working policy that denies everyone _but_ `alan@example.com`. Tested it out in a new cloud endpoint.
```
on_http_request:
- name: OAuth
actions:
- type: oauth
config:
auth_id: oauth
provider: google
- name: bad email
expressions:
- actions.ngrok.oauth.identity.email != 'alan@example.com'
actions:
- type: custom-response
config:
body: Hey, no auth for you ${actions.ngrok.oauth.identity.name}!
status_code: 400
```
In theory you could write the expression like this, which is also valid, but I feel like that makes less sense:
```
- name: bad email
expressions:
- …
```
> Fix quickstart OAuth rule

- docs/guides/other-guides/load-balancing-kubernetes-clusters.mdx
- docs/guides/other-guides/load-balancing-kubernetes.mdx
- docs/universal-gateway/endpoint-pooling.mdx
- docs/what-is-ngrok.mdx
- src/components/youtube-embed.tsx
I pushed out a new K8s-specific pooling video today, so using the new `YouTubeEmbed` component to drop it in a few places. Plus, two other pools-related tweaks:
- Fixed typos in the pooling doc
- Changed the link for **Load Balancer** in _What is ngrok?_ to point to pools.
> Add new pooling video to K8s guides

- docs/overview/index.mdx
I think the intention here is to link directly to the JS quickstart... I'm not even sure what the content of the old `/using-ngrok-with/node-js` page used to be!
> Fix broken link on homepage quickstarts

- docs/agent/upgrade-v2-v3.mdx
- sidebars.js
- static/scripts/fix-redirect.js
Move the upgrade guide to the Agent section of the docs, to get it out of the "Other Guides" section. Also clean it up a bit to give the sections proper headings
> Move the upgrade-to-v3 guide

- docs/universal-gateway/examples.mdx
- docs/universal-gateway/examples/custom-error-pages.mdx
- docs/universal-gateway/examples/front-door-pattern.mdx
- docs/universal-gateway/examples/route-by-oidc.mdx
- docs/universal-gateway/examples/secure-developer-environments.mdx
Time to keep pushing!
- Deploy Custom Error Pages
- Route to Services Based on OIDC Authentication
- Create Secure Public Developer Environments
> Add three new examples

- docs/api/resources/endpoints.mdx
- docs/universal-gateway/points-of-presence.mdx
We still have documentation that refers to Region on the Endpoint eventhough that field no longer exists on the Endpoint and Endpoints are now global.
> Remove outdated reference to endpoint regions

- docs/agent/api.md
Apropos of a recent customer issue/question (on why v3 formatted payloads were failing), I am updating the public docs of the ngrok agent API to more clearly call out that only the v2 format is supported today.
> Docs update to clarify ngrok agent API version constraints

- docs/universal-gateway/examples.mdx
- docs/universal-gateway/examples/minecraft.mdx
- docs/using-ngrok-with/minecraft.md
I felt like it was better to retain the existing Minecraft guide, and cross-link between them, because the existing Minecraft guide has info about free plans and troubleshooting that don't necessarily make sense as part of this specific example.
I couldn't help myself but do a tiny bit of cleanup in the Minecraft guide while I was in there.
> Add Minecraft example

- static/schemas/traffic-policy.json
This adds a JSON Schema for Traffic Policy that can be referenced in docs and in the dashboard. Eventually, this should be generated and served by the backend, this is temporary.
> feat: add traffic policy json schema

- docs/universal-gateway/examples.mdx
- docs/universal-gateway/examples/snippets/_back-to-examples.mdx
- src/components/ExampleHub.tsx
Noticed this because I looked at the newsletter while on vacation, tapped through to the examples gallery, and wasn't 100% happy with what I saw. Not sure how many folks actually look at our docs on mobile but this makes the experience not perfect, but far better.
> Improve mobile responsiveness in examples gallery

- static/schemas/traffic-policy.json
Updates the bucket key description on the rate limit action to be more descriptive and helpful when defining how to bucket traffic. It adds some examples.
> fix: update rate limit bucket key description

- docs/guides/other-guides/dashboard-sso-okta-setup.md
- docs/integrations/auth0/dashboard-sso.mdx
- docs/integrations/salesforce/ssowithendpoints.mdx
- docs/integrations/teams/webhooks.mdx
- docs/traffic-policy/getting-started/agent-endpoints/cli.mdx
- docs/traffic-policy/getting-started/agent-endpoints/config-file.mdx
- docs/traffic-policy/getting-started/cloud-endpoints/api.mdx
- docs/universal-gateway/kubernetes-endpoints.mdx
remove "congratulations" - doesn't suit the style and tone of technical documentation. Also took the opportunity to do some light copyediting and fix inconsistent header structures on the affected pages.
> Remove congratulations and fix header structures

- package.json
- src/components/Definition/data.ts
- src/plugins/definition-wrapper.js
- static/scripts/fix-redirect.js
Addresses issues in this slack thread:
- https://ngrok.slack.com/archives/C03LRGNSG6A/p1752619859317469
Changes:
- Updates definition wrapper script to not toss out the rest of the text if a matching term appears twice in one paragraph
- Adds a pnpm clear-cache script so it's easier to work on custom plugins. Docusaurus caches plugin output, so changes to custom plugins like the definition wrapper require clearing the cache and deleting the build folder every time
> Fix definition wrapper

- static/scripts/fix-redirect.js
This was missed in this PR:
- https://github.com/ngrok/ngrok-docs/pull/1381/files#diff-ff69966805a57bad378b3a583c5ec56f4882cf83deb4a7f31f372aff8705163c
> Redirect top level guides path

- docs/guides/identity-aware-proxy/securing-with-oauth.md
- docs/guides/migration/modules-to-traffic-policy-actions.mdx
- docs/integrations/amazon-eks/eks.mdx
- docs/integrations/azure-aks/k8s.mdx
- docs/integrations/consul/k8s.mdx
- docs/integrations/digitalocean/k8s.mdx
- docs/integrations/google-gke/google-kubernetes-engine.mdx
- docs/integrations/vcluster/k8s.md
- docs/traffic-policy/examples/add-authentication.mdx
- docs/universal-gateway/examples/route-api-app-traffic-user-agent.mdx
- static/scripts/fix-redirect.js
- traffic-policy/gallery/OAuthConditionalAccess.tsx
A check like `endsWith('example.com')` can be subverted if someone registers the domain "not-the-real-example.com", and then logs in with an email on that domain.
We should avoid suggesting something that has security issues like that.
> Suggest checking '@domain' for email checks, not just 'domain'

- docs/using-ngrok-with/docker.mdx
https://github.com/ngrok/ngrok-docs/pull/1452/commits/3c668921d0d98b0fd2d43f057a1979381e034b3e erroneously removed this page's title.
This PR puts it back.
> Add missing title for page - Using ngrok with Docker

- docs/traffic-policy/examples/a-b-tests.mdx
this example is broken. this fixes it
> fix: ab example typo

- docs/k8s/guides/using-gwapi.mdx
Add k8s Gateway API documentation on status conditions and how to view the status of Gateways.
> feat: Add k8s Gateway API status conditions documentation

- docs/using-ngrok-with/docker.mdx
This PR proposes changes to #1531 -- video is below the title but also below -the-fold.... I think we don't want it to precede the docs of the broader Docker integration. Not a strong opinion, however.
> Using ngrok with Docker Desktop - Video Demo

- docs/iam/index.mdx
Happened to notice an instance of the old "Bot user" term. Updated it to "Service user". 
(side note: I *highly* approve of the new name, it's much more clear)
> "Bot user" to "Service user"

- docs/using-ngrok-with/using-mcp.mdx
The first line says MCP stands for "Messages Control Protocol", but it's actually "Model Context Protocol".
Just to confirm I wasn't thinking of the wrong thing, I double checked in the Anthropic page linked in this first line (https://support.anthropic.com/en/articles/11175166-getting-started-with-custom-connectors-using-remote-mcp), and it agrees.
> Fixed incorrect MCP acronym

- docs/traffic-policy/secrets.mdx
X-linking between conceptual and ref docs for `secrets.get()`
> x-link to secrets macro doc

- traffic-policy/actions/oauth/config.mdx
- traffic-policy/actions/oidc/config.mdx
We recently added CEL support to the `client_id` fields of the OIDC and OAuth actions. This PR updates the docs to reflect that change
> Mark client_id field in OIDC/OAuth policies as CEL supported

- traffic-policy/actions/rate-limit/config.mdx
Expose and document the 'enforce' configuration option for rate limits.
> feat: add 'enforce' option in rate limit config

- traffic-policy/actions/redirect.mdx
Use `defaultValue` property instead of inline for `status_code` field in redirect configuration.
> Use defaultValue property for status_code in redirect.mdx

- definition-wrapper.js
Before this change, the definition wrapper's modal was always black with white text. Now, in light mode, it's white with black text.
Test it here:
- /universal-gateway/load-balancing-multiple-clouds#using-cloud-endpoints
Before:
After:
> Make definition wrapper color-mode aware
